config/routes.rb
Sflapp::Application.routes.draw do
  resources :trainers
  resources :groups
  resources :access
  resources :sections

  get 'login', :to => "access#login"
  post 'login', :to => "access#attempt_login"

    

  

  root'access#login'
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
	has_secure_password
	has_many :groups
	#accepts_nested_attributes_for :groups
	#attr_accessible :email, :password, :password_confimation

	validates_uniqueness_of :username
end


def name
	"#{trainer_name} #{last_name}"
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def index
    # display text & links
  end

  def login
    # login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_trainer = Trainer.where(:username => params[:username]).first
      if found_trainer
        authorized_trainer = found_trainer.authenticate(params[:password])
      end
    end
    if authorized_trainer
      # mark user as logged in
      session[:user_id] = authorized_trainer.id
      session[:username] = authorized_trainer.username
      flash[:notice] = "You are now logged in."
      redirect_to(:action => 'index')
    else
      flash[:notice] = "Invalid username/password combination."
      redirect_to(:action => 'login')
    end
  end

  def logout
    # mark user as logged out
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"
    redirect_to(:action => "login")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(:controller => 'access', :action => 'login')
      return false # halts the before_action
    else
      return true
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :find_trainer

  # GET /groups
  # GET /groups.json
  def index
    #@groups = @group.where(:trainer_id => @trainer.id)
    @groups = @trainer.groups
  end
  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new({:trainer_id => @trainer.id})
  end

  # GET /groups/1/edit
  def edit
    @trainer = trainer.find(params[:id])
    @groups = Group.order('position ASC')
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        flash[:notice] = "Group was successfully created"
        redirect_to(:action => 'show', :trainer_id => @current_user)
        #format.html { redirect_to :action => 'index', :trainer_id => @trainer.id, notice: 'Group was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update_attributes(group_params)
        flash[:notice] = "Group was successfully updated"
        redirect_to(:action => 'index', :trainer_id => @trainer.id)
        #format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:group_id])
    end
    def set_trainer
      @trainer = Trainer.find(params[:trainer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :trainer_id)
    end
    def find_trainer
      if params[:trainer_id]
        @trainer = Trainer.find(params[:trainer_id])
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	trainer = Trainer.find_by username(params[:username])
  	if trainer && trainer.authenticate(params[:password])
  		session[:trainer_id] = trainer.id
  		redirect_to root_url, notice: "logged in"
  	else
  		flash.now.alert = "Username or password is invalid"
  		render "new"
  	end
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in, except: [:create]
  #before_action :find_group

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
    @groups = @trainer.groups
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
    @groups = @trainer.groups
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new

  end

  # GET /trainers/1/edit
  def edit
    @trainer = Trainer.find(params[:id])
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params) 
    #@group = Group.new(group_params)
      if @trainer.save
      flash[:notice] = 'User created.'
      redirect_to(:action => 'index')
    else
      render("new")
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    @trainer = Trainer.find(params[:id])
    if @trainer.update_attributes(trainer_params)
      flash[:notice] = 'User updated'
    else
      render("edit")
    end
  end

  def delete
    @trainer = Trainer.find(params[:id])

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    Trainer.find(params[:id].destroy)
    flash[:notice] = "User destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:trainer_name, :last_name, :cell_phone_number, :user_name, :password, :password_confirmation,  groups_attributes: [ :group_name ])
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/access/index.html.erb
<% @page_title = "Admin Menu" %>
<%= flash[:message] %>
<div class="menu">
	<h2>Admin Menu</h2>
	<div class="identify">Logged in as: <%= session[:username] %></div>
	<ul>
		<li><%= link_to('Manage Groups',:controller => 'groups' )%></li>
		<li><%= link_to("Manage User", :controller => 'trainers') %></li>
		<li><%= link_to("Logout", :action => 'logout') %></li>
	</ul>
</div>

app/views/access/login.html.erb
<% @page_title = " Trainer Login" %>

<div class="login">
	<%= form_tag(:action => 'login') do %>
	<table>
		<tr>
			<td><%= label_tag(:username) %></td>
			<td><%= text_field_tag(:username) %> </td>
		</tr>
		<tr>
			<td><%= label_tag(:password) %></td>
			<td><%= password_field_tag(:password)%></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= submit_tag("Log in") %></td>
		</tr>
	</table>
	<% end %>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group, :url => { :trainer_id => @trainer.id}) do |f| %>
<table summary = "groups from trainer">
  <tr>
    <th><%= f.label(:group_name) %></th>
    <td><%= f.text_field(:group_name) %></td>
    </tr>
       <div class="actions">
    <%= f.submit %>
    </div>
      <% end %>

app/views/groups/_form2.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :trainer_id %><br>
    <%= f.number_field :trainer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> 
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>
<%= link_to 'New Group', new_group_path %>
<%= link_to "trainers", controller: 'trainers' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Trainer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= group.trainer_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.group_name %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @group.trainer_id %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sflapp</title>
  <%= stylesheet_link_tag    'application', media: "all", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Sign Up", :controller => 'trainers', :action => 'new' %> or
  <%= link_to "Log In", :controller => 'access', :action => 'login' %>

<%= yield %>

</body>
</html>

app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
<table summary = "trainers">
  <tr>
    <th><%= f.label(:trainer_name) %></th>
    <td><%= f.text_field(:trainer_name) %></td> 
    </tr>
    <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
   <tr>
    <th><%= f.label(:cell_phone_number) %></th>
    <td><%= f.text_field(:cell_phone_number) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
   <tr>
   <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
   <tr>
   	<th><%= f.label(:password_confirmation) %></th>
    <td><%= f.password_field(:password_confirmation) %></td>
  </tr>
</table>
    
       <div class="actions">
    <%= f.submit %>
    </div>
      <% end %>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<h1>Listing trainers</h1>
<%= link_to "groups", controller: 'groups' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Trainer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.trainer_name %></td>
        <td><%= trainer.id %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

<br>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render 'form' %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.trainer_name %>
</p>
<%= link_to "Add New group", :controller => 'groups', :action => 'new', :trainer_id => @trainer.id, :class => 'action new' %>|
<%= link_to "Show groups", :controller => 'groups', :action => 'index', :trainer_id => @trainer.id, :class => 'action index' %>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
          </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>